name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install Visual Studio Build Tools
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          vs-version: 2019
      - name: Build solution
        run: msbuild Sources/LeagueBot/LeagueBot.sln
