name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.302
      - name: Restore NuGet packages
        run: nuget restore Sources/LeagueBot/LeagueBot.sln
      - name: Copy patterns folder
        run: cp -r Patterns bin/
      - name: Build solution
        run: msbuild Sources/LeagueBot/LeagueBot.sln
      - name: Zip bin directory
        run: zip -r latest-dev-build.zip bin
      - name: Upload zip file
        uses: actions/upload-artifact@v2
        with:
          name: latest-dev-build.zip
          path: latest-dev-build.zip
