name: Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Install .NET Core SDK
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 3.1.302
      - name: Restore NuGet packages
        run: dotnet restore Sources/LeagueBot/LeagueBot.sln
      - name: Build solution
        run: msbuild Sources/LeagueBot/LeagueBot.sln
